### PR TITLE
boards: arm: max326xx: Add Intel hex output

### PR DESCRIPTION
**Pull request by microbuilder**
Adds the `CONFIG_BUILD_OUTPUT_HEX=y` flag to existing MAX326xx board targets, since this file is required for use with the default OpenOCD debugger.

### CODE REVIEW

**Comment by microbuilder** [comment]
Will these features be added somewhere else?

**Comment by ozersa** [comment]
It is already exist in the repository.

**Comment by microbuilder** [comment]
This isn't so much an issue inside ADI, but in the larger open source community, it's important to merge commits from the author and PR to ensure that code changes are associated with the committer. There are two reasons for this:

- The `signed-off-by` indicates that the author is assuming responsibility for the content of the PR
- Credit is often the only currency involved in open source, and people are very sensitive about the topic, and part of some companies internal reporting may well be how many contributions an author made to a project, which is generally collected via analysing git log for an author name.

I wanted to check how this was done here, just because it's an important thing for us to get right now before we open this work up, but it looks like we've changed the branch we're working off? On `main` I don't even see the MAX326xx boards here anymore: https://github.com/analogdevicesinc/zephyr/tree/main/boards/arm ... which branch should future PRs be based off, and can you point me to where these changes were added in tree?

**Comment by microbuilder** [comment]
Sorry, to answer my own question, I didn't notice this wasn't the inner-source repo (https://github.com/analogdevicesinc/zephyr/pull/6#issuecomment-1784829316). 🤦‍♂️

**Pull request closed without merging**
